import { StyleSheet } from 'react-native';


const styles = StyleSheet.create({
    container: {
        flexGrow: 1,
        backgroundColor: '#e9ecef',
        alignItems: 'center',
        justifyContent: 'flex-start',
        padding: 24,
        minHeight: '100%',
    },
    titulo: {
        fontSize: 30,
        fontWeight: 'bold',
        color: '#22223b',
        marginBottom: 28,
        textAlign: 'center',
        letterSpacing: 1,
    },
    label: {
        fontSize: 16,
        color: '#4a4e69',
        marginBottom: 6,
        alignSelf: 'flex-start',
        marginLeft: 8,
    },
    input: {
        width: '100%',
        height: 48,
        backgroundColor: '#fff',
        borderRadius: 12,
        paddingHorizontal: 18,
        marginBottom: 18,
        fontSize: 16,
        borderWidth: 1.5,
        borderColor: '#bfc0c0',
        shadowColor: '#22223b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    areaBotoes: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
        marginTop: 10,
        marginBottom: 28,
    },
    botao: {
        flex: 1,
        backgroundColor: '#38b000',
        paddingVertical: 15,
        borderRadius: 10,
        marginRight: 8,
        alignItems: 'center',
        shadowColor: '#22223b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 2,
    },
    botaoCancelar: {
        flex: 1,
        backgroundColor: '#d90429',
        paddingVertical: 15,
        borderRadius: 10,
        marginLeft: 8,
        alignItems: 'center',
        shadowColor: '#22223b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.15,
        shadowRadius: 4,
        elevation: 2,
    },
    textoBotao: {
        color: '#fff',
        fontSize: 17,
        fontWeight: 'bold',
        letterSpacing: 0.5,
    },
    codigoContainer: {
        width: '100%',
        height: 48,
        backgroundColor: '#f7f7f7',
        borderRadius: 12,
        justifyContent: 'center',
        paddingHorizontal: 18,
        marginBottom: 18,
        borderWidth: 1.5,
        borderColor: '#bfc0c0',
        shadowColor: '#22223b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    codigoTexto: {
        color: '#22223b',
        fontSize: 16,
    },
    codigoTextoVazio: {
        color: '#aaa',
    },
    // Cartão de contato
    cardContato: {
        width: '100%',
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 16,
        marginVertical: 7,
        borderWidth: 1.5,
        borderColor: '#bfc0c0',
        shadowColor: '#22223b',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.10,
        shadowRadius: 6,
        elevation: 3,
    },
});

export default styles;
